# fly.toml app configuration file generated for misty-river-3857 on 2023-08-09T11:52:35+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "misty-river-3857"
primary_region = "ams"

[build]
  [build.args]
    NODE_VERSION = "19"

[processes]
  web = "node --experimental-wasi-unstable-preview1 server.mjs"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["web"]
